# This script is maintained centrally by the LDT4SSC consortium.
# The canonical version lives at:
#   https://github.com/ldt4ssc/ldt4ssc.github.io/blob/main/docs/assets/validate_updates.py
#
# The validation workflow fetches it directly from there at runtime.
# Do not edit this file; changes here have no effect.
